import RootLayout from "@/components/layout";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RootLayout>
        <div className="col-span-3 lg:col-span-4 border-l boder-l-slate-700">
          <div className="h-full px-8 py-6"></div>
        </div>
      </RootLayout>
    </>
  );
}
